INFO:werkzeug:127.0.0.1 - - [04/Jul/2024 23:59:54] "OPTIONS /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [04/Jul/2024 23:59:54] "GET /evento HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:33] "OPTIONS /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:33] "GET /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77008 and this is thread id 68780.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532097B0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77008 and this is thread id 68780.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77008 and this is thread id 68780.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:35] "GET /eventoporid?id=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todas as salas
DEBUG:root:Consulta todos os centrodeinteresses
DEBUG:root:Consulta todos os participantes
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:35] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:35] "GET /sala HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:35] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:35] "GET /participante?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:36] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:36] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:36] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:37] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:37] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todas as salas
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:01:37] "GET /sala HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centros de interesse
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 72064 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A5C0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 72064 and this is thread id 80164.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 72064 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71084 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308F3D0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71084 and this is thread id 80164.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71084 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80952 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A890>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80952 and this is thread id 80164.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80952 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81696 and this is thread id 80164.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835312CD60>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81696 and this is thread id 80164.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81696 and this is thread id 80164.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:18] "GET /participante/centrosdeinteresse?eventoId=10 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centros de interesse
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:25] "GET /participante/centrosdeinteresse?eventoId=10 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centros de interesse
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:32] "GET /participante/centrosdeinteresse?eventoId=4 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /eventoporid?id=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todas as salas
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /sala HTTP/1.1" 200 -
DEBUG:root:Consulta todos os participantes
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75196 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209210>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75196 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75196 and this is thread id 76020.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /participante?eventoId=1 HTTP/1.1" 200 -
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68780 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308EA70>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68780 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68780 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81616 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532098A0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81616 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81616 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 30112 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209B70>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 30112 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 30112 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80420 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308F790>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80420 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80420 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 69408 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532095D0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 69408 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 69408 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1444 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209E40>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1444 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1444 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71368 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A020>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71368 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 71368 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80164 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320AC50>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80164 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80164 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 78008 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A6B0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 78008 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 78008 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320B5B0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75088 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320B970>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75088 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 75088 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68712 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320BD30>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68712 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68712 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 57788 and this is thread id 76020.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320BF10>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 57788 and this is thread id 76020.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 57788 and this is thread id 76020.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:41] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:42] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:42] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todas as salas
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:42] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:42] "GET /sala HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:42] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centros de interesse
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:06:52] "GET /participante/centrosdeinteresse?eventoId=9 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:01] "OPTIONS /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74996 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308F3D0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74996 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74996 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308DC60>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 41192 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74656 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320BC40>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74656 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74656 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77032 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320BA60>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77032 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77032 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 45632 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A4D0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 45632 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 45632 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 61324 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A890>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 61324 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 61324 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67996 and this is thread id 63300.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835312CD60>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67996 and this is thread id 63300.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67996 and this is thread id 63300.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:01] "GET /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:04] "GET /eventoporid?id=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todas as salas
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
DEBUG:root:Consulta todos os participantes
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /sala HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /participante?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:05] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66484 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308DF30>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66484 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66484 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68128 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353208F40>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68128 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68128 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10424 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A5C0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10424 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 10424 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81760 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532097B0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81760 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81760 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81640 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209030>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81640 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81640 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80756 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209F30>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80756 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80756 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80472 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532096C0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80472 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80472 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79008 and this is thread id 82412.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209A80>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79008 and this is thread id 82412.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79008 and this is thread id 82412.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:06] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todas as salas
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:06] "GET /sala HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:06] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:42] "OPTIONS /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:43] "GET /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:44] "GET /eventoporid?id=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todas as salas
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todos os centrodeinteresses
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532089A0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /sala HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68224 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209120>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68224 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 68224 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82168 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308DE40>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82168 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82168 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77372 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183532094E0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77372 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77372 and this is thread id 79156.
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os participantes
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /participante?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:10:45] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:12:55] "OPTIONS /evento HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:12:56] "[31m[1mGET /evento HTTP/1.1[0m" 403 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:13:01] "OPTIONS /evento HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:13:02] "[31m[1mGET /evento HTTP/1.1[0m" 403 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:13:19] "OPTIONS /evento HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:13:20] "[31m[1mGET /evento HTTP/1.1[0m" 403 -
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74300 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835312F2E0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74300 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 74300 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 76020 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183533084F0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 76020 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 76020 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79424 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183533087C0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79424 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79424 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79260 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835308D990>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79260 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 79260 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80828 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A2F0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80828 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80828 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80880 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320B6A0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80880 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 80880 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77464 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x00000183533089A0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77464 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 77464 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81988 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320BB50>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81988 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 81988 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 63300 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A200>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 63300 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 63300 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82412 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353209300>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82412 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 82412 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x000001835320A7A0>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 66644 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67204 and this is thread id 79156.
ERROR:sqlalchemy.pool.impl.NullPool:Exception closing connection <sqlite3.Connection object at 0x0000018353308040>
Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 753, in _finalize_fairy
    fairy._reset(pool)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1004, in _reset
    pool._dialect.do_rollback(self)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 683, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67204 and this is thread id 79156.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\pool\base.py", line 255, in _close_connection
    self._dialect.do_terminate(connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 689, in do_terminate
    self.do_close(dbapi_connection)
  File "c:\Estudo\Pós\Sprint Arquitetura de Software\MVP\Legado\eventosapi\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 692, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 67204 and this is thread id 79156.
INFO:werkzeug: * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:03] "OPTIONS /evento HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:03] "[31m[1mGET /evento HTTP/1.1[0m" 403 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:15] "OPTIONS /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:15] "GET /evento HTTP/1.1" 200 -
DEBUG:root:Consulta todos os eventos
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:16] "GET /eventoporid?id=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todas as salas
DEBUG:root:Consulta todos os centrodeinteresses
DEBUG:root:Consulta todos os participantes
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /sala HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /participante?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os responsavels
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /responsavel?eventoid=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
DEBUG:root:Consulta todos os centrodeinteresses
INFO:werkzeug:127.0.0.1 - - [05/Jul/2024 00:14:17] "GET /centrodeinteresse?eventoId=1 HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:39] "[32mGET /openapi HTTP/1.1[0m" 308 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:39] "GET /openapi/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:39] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:39] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:39] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:42] "GET /openapi/swagger HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:42] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:42] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:42] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:43] "GET /openapi/openapi.json HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:47] "GET /openapi/swagger HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:48] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:48] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:48] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [06/Jul/2024 12:53:48] "GET /openapi/openapi.json HTTP/1.1" 200 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
